# Generated by Django 5.0.6 on 2026-05-11 21:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLLMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('llama-3.1-8b-instant', 'Llama 3.1 8B (Rápido - Recomendado)'), ('llama-3.1-70b-versatile', 'Llama 3.1 70B (Versátil)'), ('mixtral-8x7b-32768', 'Mixtral 8x7B (Balance)'), ('gemma-7b-it', 'Gemma 7B (Ligero)')], default='llama-3.1-8b-instant', help_text='Modelo de Groq a usar', max_length=100)),
                ('temperature', models.FloatField(default=0.7, help_text='Temperatura (0=determinístico, 1=creativo)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('max_tokens', models.IntegerField(default=1024, help_text='Máximo de tokens en la respuesta', validators=[django.core.validators.MinValueValidator(256), django.core.validators.MaxValueValidator(4096)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Usuario propietario de estas configuraciones', on_delete=django.db.models.deletion.CASCADE, related_name='llm_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de LLM del Usuario',
                'verbose_name_plural': 'Configuraciones de LLM',
                'ordering': ['-updated_at'],
            },
        ),
    ]
